### ISSUE TITLE
Restore deployment to drat

### ISSUE THREAD

**Issue by jakejh** [hugheylab/deltaccd#2]
@JSchoenbachler it seems your commit on June 23 inappropriately disabled drat deployment. Please fix this on all the public R package repos except for simphony, which I just fixed separately.

https://github.com/hugheylab/deltaccd/blob/0798073b392052a6bb71d62414804229cad1e003/.circleci/config.yml#L125

**Comment by JSchoenbachler** [comment]
Done on this repo (deltaccd), zeitzeiger, and tipa. Limorhyde was fine, and as you just said you fixed Simphony yourself. Sorry for the delay!

**Comment by jakejh** [comment]
Why did your deltaccd commit deploy to drat, though?

**Comment by JSchoenbachler** [comment]
Probably because this commit https://github.com/hugheylab/deltaccd/commit/e3c18f5d6429a9d002adb4c7a12a3b980f62d652 was when it was disabled, and since then we have added "NEWS.md" to .Rbuildignore.

**Comment by jakejh** [comment]
Same for tipa?

**Comment by JSchoenbachler** [comment]
Yep, this commit: https://github.com/hugheylab/tipa/commit/6f0593c7b7c525720c8e23c7c11e68c7115c4aed
