### ISSUE TITLE
misleading assignment of rownames

### ISSUE THREAD

**Issue by jakejh** [hugheylab/deltaccd#6]
looks like rownames will be integers, but what does R silently convert them to?

https://github.com/hugheylab/deltaccd/blob/4ba72f1ae53b2e1556ed193b6d050ed23605365b/tests/testthat/test_non_exported.R#L30

**Comment by ehoutland** [comment]
They get converted to characters. Do you think I should just make the rownames something like c('a', 'b') instead? Or just do as.character(1:2)?

**Comment by jakejh** [comment]
Don't make the gene names the same as the condition names. I often try to implicitly document the code by doing stuff like `paste0('gene_', 1:2)`.
